In [1]:
# 入力
import numpy as np

N = 2
M = 3
base = np.array([400, 410, 420])
h = np.array([[400, 400, 400],[300, 300, 300]])

In [2]:
# 正解からの差を計算
dif = h - base
dif

array([[   0,  -10,  -20],
       [-100, -110, -120]])

In [3]:
abs(dif[0,1])

np.int64(10)

In [4]:
deduction = []
deduction.append(0)
deduction.append(1)
deduction

[0, 1]

In [5]:
deduction = np.zeros_like(dif)
deduction

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
# 減点計算
deduction = np.zeros_like(dif)
for n in range(N):
    for m in range(M):
        if abs(dif[n,m]) <= 5:
            deduction[n,m] += 0
        elif abs(dif[n,m]) <= 10:
            deduction[n,m] += 1
        elif abs(dif[n,m]) <= 20:
            deduction[n,m] += 2
        elif abs(dif[n,m]) <= 30:
            deduction[n,m] += 3
        else:
            deduction[n,m] += 5

deduction

deduction_person = np.sum(deduction, axis=1)
deduction_person

array([ 3, 15])

In [9]:
# 得点計算
point = 100 - deduction_person
point

array([97, 85])

In [12]:
# 最高点出力
print(np.maximum(0,point).max())

97
